from django.urls import path
from . import views
urlpatterns = [
    path("notes/",                          views.notes_list,     name="notes_list"),
    path("notes/create/",                   views.note_create,    name="note_create"),
    path("notes/<int:pk>/",                 views.note_detail,    name="note_detail"),
    path("notes/<int:pk>/edit/",            views.note_edit,      name="note_edit"),
    path("notes/<int:pk>/delete/",          views.note_delete,    name="note_delete"),
    path("snippets/",                       views.snippets_list,  name="snippets_list"),
    path("snippets/create/",                views.snippet_create, name="snippet_create"),
    path("snippets/<int:pk>/",              views.snippet_detail, name="snippet_detail"),
    path("snippets/<int:pk>/edit/",         views.snippet_edit,   name="snippet_edit"),
    path("snippets/<int:pk>/delete/",       views.snippet_delete, name="snippet_delete"),
    path("snippets/<int:pk>/publish/",      views.snippet_publish,name="snippet_publish"),
    path("tasks/",                          views.tasks_board,    name="tasks_board"),
    path("tasks/create/",                   views.task_create,    name="task_create"),
    path("tasks/<int:pk>/edit/",            views.task_edit,      name="task_edit"),
    path("tasks/<int:pk>/delete/",          views.task_delete,    name="task_delete"),
    path("tasks/<int:pk>/move/<str:new_status>/", views.task_move, name="task_move"),
    path("events/",                         views.events_calendar,name="events_calendar"),
    path("events/create/",                  views.event_create,   name="event_create"),
    path("focus/",                          views.focus_timer,    name="focus_timer"),
    path("focus/start/",                    views.focus_start,    name="focus_start"),
    path("achievements/",                   views.achievements,   name="achievements"),
    path("search/",                         views.search,         name="search"),
    path("profile/",                        views.profile,        name="profile"),
    path("share/settings/",                 views.share_settings, name="share_settings"),
    path("u/<str:username>/",               views.public_profile, name="public_profile"),
]
